// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// pcNetCoreRcpp
arma::mat pcNetCoreRcpp(const arma::mat& X_std, int nComp);
RcppExport SEXP _scTenifoldNet_pcNetCoreRcpp(SEXP X_stdSEXP, SEXP nCompSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X_std(X_stdSEXP);
    Rcpp::traits::input_parameter< int >::type nComp(nCompSEXP);
    rcpp_result_gen = Rcpp::wrap(pcNetCoreRcpp(X_std, nComp));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_scTenifoldNet_pcNetCoreRcpp", (DL_FUNC) &_scTenifoldNet_pcNetCoreRcpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_scTenifoldNet(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
