# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Core PC Network computation (C++ backend)
#'
#' @description Computes the gene coefficient matrix using principal component
#' regression. For each gene K, regresses it against principal components
#' derived from all other genes via truncated SVD.
#'
#' @param X_std A standardized numeric matrix (samples x genes), centered
#'   and scaled by column.
#' @param nComp Number of principal components to use.
#'
#' @return A numeric matrix (n_genes x (n_genes - 1)) of regression coefficients.
#'
#' @keywords internal
pcNetCoreRcpp <- function(X_std, nComp) {
    .Call(`_scTenifoldNet_pcNetCoreRcpp`, X_std, nComp)
}

