#' @export tensorDecomposition
#' @importFrom rTensor cp
#' 
#' @title tensorDecomposition
#' @description ...
#' @param xList ...
#' @param yList ...
#' @param d ...
#' @return ...
#' @references ...
#' @details ...

tensorDecomposition <- function(xList, yList, d = 5){

}
